# Render deployment configuration for Movie_Finding_Made_Easy

services:
  - type: web
    name: Movie_Finding_Made_Easy
    env: php
    region: oregon   
    branch: main
    rootDir: .                  
    buildCommand: ""           
    startCommand: "php -S 0.0.0.0:$PORT router.php"
    phpVersion: "8.1"           
    autoDeploy: true            # automatically deploy on each push
