# .render.yaml
services:
  - type: web
    name: Movie_Finding_Made_Easy
    env: php
    region: oregon         
    branch: main
    rootDir:           
    buildCommand: 
    startCommand: "php -S 0.0.0.0:$PORT -t ."
    phpVersion: "8.1"      # pick 8.0 or 8.1
